"use strict";
var fname = 'sudhanshu';
console.log(fname);
var lname;
lname = 'gupta';
console.log(lname);
var age;
age = 20;
console.log(age);
console.log("age : " + age);
console.log(age.toString());
var empList;
empList = ["Sudhanshu1", 'Sudhanshu2', 'Sudhanshu3', 10];
var deptList;
deptList = ["Sudhanshu1", 'Sudhanshu2', 'Sudhanshu3'];
var sudhanshu = age.toString();
console.log(empList);
console.log(deptList);
var numList = [10, 2, 13, 4, 3];
console.log(typeof numList);
var sum = numList.reduce((acc, num) => acc / num);
console.log(sum);
console.log(1 /* color.blue */);
